# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22.12.0
    commands:
      - echo Installing Mocha...
  pre_build:
    commands:
      - apt-get install build-essential
      - echo Installing source NPM dependencies...
      - cd frontend
      - npm i yarn -g
      - yarn add bcrypt-nodejs
      - yarn install
      - echo installing angular at global
      - node -v
      - npm -v
  build:
    commands:
      - echo pwd
      - pwd
      - echo Build started on `date`
      - node_modules/@angular/cli/bin/ng build --aot --prod
artifacts:
  files:
    - 'frontend/dist/**/*'
    - 'appspec.yml'
    - 'frontend/runpp.sh'
    - 'frontend/node_modules/**/*'
    
