version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update -y
      - apt-get install -y awscli

  pre_build:
    commands:
      - echo "Preparing to deploy to S3..."
      - aws --version

  build:
    commands:
      - echo "Building project..."
      - rm -rf node_modules
      - rm -f package-lock.json
      - npm install --legacy-peer-deps
      - npm run build
      - echo "Build complete."

  post_build:
    commands:
      - echo "Deploying to S3..."
      - aws s3 sync ./dist s3://vmrda-rental-code/build/ --acl public-read --delete
      - echo "Deployment complete."

artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: /